import { LINT_RULES } from "./rules.js";

/** The lint rule reference (README, WEB-1 docs), generated from the rule definitions. */
export function ruleReference(): string {
  const table = [
    "| Rule | Default | What it catches |",
    "|---|---|---|",
    ...LINT_RULES.map((r) => `| [\`${r.id}\`](#${r.id}) | ${r.severity} | ${r.summary} |`),
  ];
  const sections = LINT_RULES.map((r) =>
    [
      `### ${r.id}`,
      "",
      `**${r.severity}.** ${r.summary} ${r.why}`,
      "",
      "Bad:",
      "",
      "```markdown",
      r.bad,
      "```",
      "",
      "Good:",
      "",
      "```markdown",
      r.good,
      "```",
      ...(r.fixDescription ? ["", `Fix: ${r.fixDescription}`] : []),
    ].join("\n"),
  );
  return [table.join("\n"), ...sections].join("\n\n");
}

export const RULES_START =
  "<!-- lint-rules:start (generated by `pnpm --filter ./packages/spec gen:rule-docs`) -->";
export const RULES_END = "<!-- lint-rules:end -->";
