import { brand } from "@testament/brand";
import { hash16 } from "@testament/spec";

// Every generated file starts with a header. Its content hash covers the whole
// file (with the hash itself blanked), so a hand edit anywhere is detected and
// regeneration refuses to overwrite it without --force (guarantee 6).

export interface Header {
  /** Project-relative test path, or a description for shared files. */
  from: string;
  /** Recording file the spec was generated from (specs only). */
  recording?: string;
  /** Hashed into the header: what in the recording the code came from. */
  recordingKey?: string;
  /** Comment marker: `//` (TypeScript, the default) or `#` (YAML: Maestro flows). */
  comment?: "//" | "#";
}

const HASH_LINE = /^(\/\/|#) Content hash: ([0-9a-f]{16})$/m;
const BLANK_HASH = "0".repeat(16);
export const DOCS_URL = `https://${brand.domain}/docs/generated-specs`;

function hashOf(content: string): string {
  return hash16(
    content.replace(HASH_LINE, (_line, marker: string) => `${marker} Content hash: ${BLANK_HASH}`),
  );
}

/** Puts the header on top of `body` and fills in the content hash. */
export function withHeader(body: string, header: Header): string {
  const c = header.comment ?? "//";
  const lines = [
    `${c} Generated by ${brand.productName} from ${header.from}. Safe to edit: see ${DOCS_URL}`,
    `${c} (${brand.productName} won't overwrite a changed file unless you pass --force).`,
  ];
  if (header.recording) {
    lines.push(`${c} Recording: ${header.recording} (key ${hash16(header.recordingKey ?? "")})`);
  }
  lines.push(`${c} Content hash: ${BLANK_HASH}`);
  const content = `${lines.join("\n")}\n${body.startsWith("\n") ? "" : "\n"}${body}`;
  return content.replace(HASH_LINE, `${c} Content hash: ${hashOf(content)}`);
}

export type FileState =
  /** Our header, and the content still matches its hash. */
  | "generated"
  /** Our header, but the content changed since it was generated. */
  | "edited"
  /** No generated header: someone else's file. */
  | "foreign";

/** Whether an existing file is untouched generated output. */
export function fileState(content: string): FileState {
  const match = HASH_LINE.exec(content);
  if (!match) return "foreign";
  return hashOf(content) === match[2] ? "generated" : "edited";
}
