// Generated by Optestra from the environment "local". Safe to edit: see https://optestra.com/docs/generated-specs
// (Optestra won't overwrite a changed file unless you pass --force).
// Content hash: 419eace570fdde93

import type { FullConfig } from "@playwright/test";
import { scrubFolder } from "./optestra.reporter";

/**
 * After the whole run: scrubs secrets out of every trace in the output folders.
 * A backstop for runs where `--reporter` replaced the scrubbing reporter.
 */
export default function scrubAfterRun(config: FullConfig): void {
  for (const project of config.projects) scrubFolder(project.outputDir);
}
