// Generated by Optestra from the environment "local". Safe to edit: see https://optestra.com/docs/generated-specs
// (Optestra won't overwrite a changed file unless you pass --force).
// Content hash: db16ae36f40ca46b

import { defineConfig, devices } from "@playwright/test";

// Runs the generated specs with plain Playwright, no Optestra needed:
//   npx playwright test -c tests/.optestra
// Point them at another site with OPTESTRA_BASE_URL (and OPTESTRA_ALLOWED_DOMAINS).
export default defineConfig({
  testDir: ".",
  testMatch: "*.spec.ts",
  timeout: 300_000,
  retries: 1,
  // The second reporter scrubs secrets out of every trace that is kept; the
  // global teardown does it again after the run, whatever the reporters.
  reporter: [[process.env.CI ? "dot" : "list"], ["./optestra.reporter.ts"]],
  globalTeardown: "./optestra.teardown.ts",
  use: {
    baseURL: process.env.OPTESTRA_BASE_URL ?? "http://127.0.0.1:4100",
    actionTimeout: 5_000,
    navigationTimeout: 30_000,
    serviceWorkers: "block",
    acceptDownloads: false,
    trace: "retain-on-failure",
    video: "retain-on-failure",
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
    { name: "firefox", use: { ...devices["Desktop Firefox"] } },
    { name: "webkit", use: { ...devices["Desktop Safari"] } },
  ],
});
