// Generated by Optestra from tests/billing-zero-due.test.md. Safe to edit: see https://optestra.com/docs/generated-specs
// (Optestra won't overwrite a changed file unless you pass --force).
// Recording: tests__billing-zero-due.steps.json (key 70cf52efb1e06858)
// Content hash: cb479a5e7a4bd0d4

import { allowed, expect, test } from "./optestra.fixtures";

test.beforeEach(async ({ page }) => {
  // setup: POST /__test/seed
  const seed = await page.request.post(allowed("/__test/seed"), {
    data: { trial: "pro" },
    maxRedirects: 0,
  });
  await expect(seed, "setup: POST /__test/seed").toBeOK();
});

test("A trial costs nothing today", { tag: ["@payments"] }, async ({ page, secrets }) => {
  const loginParams = { email: "ada@example.com" };
  // auth: ada. Optestra reuses a saved session; this spec logs in each time.
  await test.step("auth: ada (tests/flows/login.test.md)", async () => {
    // 1. Go to /login
    await test.step("Go to /login", async () => {
      await page.goto("/login");
    });

    // 2. Fill "Email" with {{params.email}}
    await test.step('Fill "Email" with {{params.email}}', async () => {
      // 2 fallback locators recorded: Optestra can heal this.
      await page.getByRole("textbox", { name: "Email", exact: true }).fill(loginParams.email);
    });

    // 3. Fill "Password" with {{params.password}}
    await test.step('Fill "Password" with {{params.password}}', async () => {
      // 2 fallback locators recorded: Optestra can heal this.
      await secrets.fill(
        page.getByRole("textbox", { name: "Password", exact: true }),
        "SHOP_PASSWORD",
      );
    });

    // 4. Click "Log in"
    await test.step('Click "Log in"', async () => {
      // 2 fallback locators recorded: Optestra can heal this.
      await page.getByRole("button", { name: "Log in", exact: true }).click();
    });

    // 5. Expect: the page heading is "Dashboard"
    await test.step('Expect: the page heading is "Dashboard"', async () => {
      await expect(page.getByRole("heading", { level: 1 })).toHaveText("Dashboard");
    });
  });

  // Start: /dashboard
  await page.goto("/dashboard");

  // 1. Go to the billing page
  await test.step("Go to the billing page", async () => {
    // 2 fallback locators recorded: Optestra can heal this.
    await page.getByRole("link", { name: "Billing", exact: true }).click();
  });

  // 2. Expect: the page shows "Pro plan"
  await test.step('Expect: the page shows "Pro plan"', async () => {
    await expect(page.getByText("Pro plan")).toBeVisible();
  });

  // 3. Expect: the page shows "$0.00 due today"
  await test.step('Expect: the page shows "$0.00 due today"', async () => {
    await expect(page.getByText("$0.00 due today", { exact: true })).toBeVisible();
  });
});
