// Generated by Optestra from tests/avatar-upload.test.md. Safe to edit: see https://optestra.com/docs/generated-specs
// (Optestra won't overwrite a changed file unless you pass --force).
// Recording: tests__avatar-upload.steps.json (key 4c150e1b32e8f389)
// Content hash: 34311eb1a362f32a

import { allowed, expect, route, test, upload } from "./optestra.fixtures";

test.beforeEach(async ({ page }) => {
  // setup: POST /__test/seed
  const seed = await page.request.post(allowed("/__test/seed"), { maxRedirects: 0 });
  await expect(seed, "setup: POST /__test/seed").toBeOK();
});

test("A user can upload an avatar", { tag: ["@settings", "@files"] }, async ({ page, secrets }) => {
  // Start: /login
  await page.goto("/login");

  const loginParams = { email: "ada@example.com" };
  // 1. Use: flows/login.test.md
  await test.step("Log in (flows/login.test.md)", async () => {
    // 1. Go to /login
    await test.step("Go to /login", async () => {
      await page.goto("/login");
    });

    // 2. Fill "Email" with {{params.email}}
    await test.step('Fill "Email" with {{params.email}}', async () => {
      // 2 fallback locators recorded: Optestra can heal this.
      await page.getByRole("textbox", { name: "Email", exact: true }).fill(loginParams.email);
    });

    // 3. Fill "Password" with {{params.password}}
    await test.step('Fill "Password" with {{params.password}}', async () => {
      // 1 fallback locator recorded: Optestra can heal this.
      await secrets.fill(page.getByLabel("Password", { exact: true }), "SHOP_PASSWORD");
    });

    // 4. Click "Log in"
    await test.step('Click "Log in"', async () => {
      // 2 fallback locators recorded: Optestra can heal this.
      await page.getByRole("button", { name: "Log in", exact: true }).click();
    });

    // 5. Expect: the page heading is "Dashboard"
    await test.step('Expect: the page heading is "Dashboard"', async () => {
      await expect(page.locator("h1")).toHaveText("Dashboard");
    });
  });

  // 2. Go to the settings page
  await test.step("Go to the settings page", async () => {
    // 2 fallback locators recorded: Optestra can heal this.
    await page.getByRole("link", { name: "Settings", exact: true }).click();
    await expect(page).toHaveURL(route("/settings"));
  });

  // 3. Upload files/avatar.png to "Choose an image"
  await test.step('Upload files/avatar.png to "Choose an image"', async () => {
    // 1 fallback locator recorded: Optestra can heal this.
    await upload(page.getByLabel("Choose an image", { exact: true }), ["../files/avatar.png"]);
  });

  // 4. Click "Upload avatar"
  await test.step('Click "Upload avatar"', async () => {
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByRole("button", { name: "Upload avatar", exact: true }).click();
  });

  // 5. Expect: a message says "Avatar updated"
  await test.step('Expect: a message says "Avatar updated"', async () => {
    await expect(page.getByText("Avatar updated", { exact: true })).toBeVisible();
  });

  // 6. Expect: the image "Your avatar" is visible
  await test.step('Expect: the image "Your avatar" is visible', async () => {
    await expect(page.getByRole("img", { name: "Your avatar", exact: true })).toBeVisible();
  });
});
