// Generated by Optestra from tests/create-project.test.md. Safe to edit: see https://optestra.com/docs/generated-specs
// (Optestra won't overwrite a changed file unless you pass --force).
// Recording: tests__create-project.steps.json (key c5addf002929cb99)
// Content hash: dac8af9f50dcd43a

import { allowed, expect, test } from "./optestra.fixtures";

test.beforeEach(async ({ page }) => {
  // setup: POST /__test/seed
  const seed = await page.request.post(allowed("/__test/seed"), { maxRedirects: 0 });
  await expect(seed, "setup: POST /__test/seed").toBeOK();
});

test("A new project is saved", { tag: ["@smoke", "@projects"] }, async ({ page, secrets }) => {
  // Start: /login
  await page.goto("/login");

  const loginParams = { email: "ada@example.com" };
  // 1. Use: flows/login.test.md
  await test.step("Log in (flows/login.test.md)", async () => {
    // 1. Go to /login
    await test.step("Go to /login", async () => {
      await page.goto("/login");
    });

    // 2. Fill "Email" with {{params.email}}
    await test.step('Fill "Email" with {{params.email}}', async () => {
      // 2 fallback locators recorded: Optestra can heal this.
      await page.getByRole("textbox", { name: "Email", exact: true }).fill(loginParams.email);
    });

    // 3. Fill "Password" with {{params.password}}
    await test.step('Fill "Password" with {{params.password}}', async () => {
      // 1 fallback locator recorded: Optestra can heal this.
      await secrets.fill(page.getByLabel("Password", { exact: true }), "SHOP_PASSWORD");
    });

    // 4. Click "Log in"
    await test.step('Click "Log in"', async () => {
      // 2 fallback locators recorded: Optestra can heal this.
      await page.getByRole("button", { name: "Log in", exact: true }).click();
    });

    // 5. Expect: the page heading is "Dashboard"
    await test.step('Expect: the page heading is "Dashboard"', async () => {
      await expect(page.locator("h1")).toHaveText("Dashboard");
    });
  });

  // 2. Click "Create project"
  await test.step('Click "Create project"', async () => {
    // 2 fallback locators recorded: Optestra can heal this.
    await page.getByRole("button", { name: "Create project", exact: true }).click();
  });

  // 3. Expect: a dialog titled "New project" is open
  await test.step('Expect: a dialog titled "New project" is open', async () => {
    await expect(page.getByRole("dialog", { name: "New project", exact: true })).toBeVisible();
  });

  // 4. Fill "Project name" with Q3 roadmap
  await test.step('Fill "Project name" with Q3 roadmap', async () => {
    // 2 fallback locators recorded: Optestra can heal this.
    await page.getByLabel("Project name", { exact: true }).fill("Q3 roadmap");
  });

  // 5. Click "Create"
  await test.step('Click "Create"', async () => {
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByRole("button", { name: "Create", exact: true }).click();
  });

  // 6. Expect: a message says "Project created"
  await test.step('Expect: a message says "Project created"', async () => {
    await expect(page.getByText("Project created", { exact: true })).toBeVisible();
  });

  // 7. Expect: the projects list shows "Q3 roadmap"
  await test.step('Expect: the projects list shows "Q3 roadmap"', async () => {
    await expect(
      page
        .getByRole("list", { name: "Projects", exact: true })
        .getByText("Q3 roadmap", { exact: true }),
    ).toBeVisible();
  });

  // 8. Reload the page
  await test.step("Reload the page", async () => {
    await page.reload();
  });

  // 9. Expect: the projects list shows "Q3 roadmap"
  await test.step('Expect: the projects list shows "Q3 roadmap"', async () => {
    await expect(
      page
        .getByRole("list", { name: "Projects", exact: true })
        .getByText("Q3 roadmap", { exact: true }),
    ).toBeVisible();
  });
});
