// Generated by Optestra from tests/checkout-trial.test.md. Safe to edit: see https://optestra.com/docs/generated-specs
// (Optestra won't overwrite a changed file unless you pass --force).
// Recording: tests__checkout-trial.steps.json (key d9b62f0fc12dc08f)
// Content hash: 9eec5c3d63868982

import { expect, route, test } from "./optestra.fixtures";

test("New customer can start a Pro trial", {
  tag: ["@smoke", "@payments"],
  annotation: [
    { type: "optestra", description: 'Never: click "Delete account" (checked by Optestra only)' },
  ],
}, async ({ page, values, secrets, inbox }) => {
  test.setTimeout(180_000);
  const data = { email: values.unique.email() };

  // Start: /pricing
  await page.goto("/pricing");

  // 1. Click "Start free trial" on the Pro plan
  await test.step('Click "Start free trial" on the Pro plan', async () => {
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByRole("button", { name: "Start free trial", exact: true }).nth(1).click();
    await expect(page).toHaveURL(route("/signup"));
  });

  // 2. Sign up with {{data.email}} and password {{secret.SHOP_PASSWORD}}
  await test.step("Sign up with {{data.email}} and password {{secret.SHOP_PASSWORD}}", async () => {
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByLabel("Email", { exact: true }).fill(data.email);
    // 1 fallback locator recorded: Optestra can heal this.
    await secrets.fill(page.getByLabel("Password", { exact: true }), "SHOP_PASSWORD");
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByRole("button", { name: "Sign up", exact: true }).click();
  });

  // 3. Expect: the page heading is "Check your email"
  await test.step('Expect: the page heading is "Check your email"', async () => {
    await expect(page.locator("h1")).toHaveText("Check your email");
  });

  // 4. Enter the code from the verification email and click "Verify"
  await test.step('Enter the code from the verification email and click "Verify"', async () => {
    const inboxCode = await inbox.code();
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByLabel("Verification code", { exact: true }).fill(inboxCode);
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByRole("button", { name: "Verify", exact: true }).click();
    await expect(page).toHaveURL(route("/checkout"));
  });

  // 5. Fill the card form with test card 4242 4242 4242 4242, expiry 12/34, CVC 123
  await test.step("Fill the card form with test card 4242 4242 4242 4242, expiry 12/34, CVC 123", async () => {
    await page
      .getByTitle("Secure card payment", { exact: true })
      .contentFrame()
      .getByRole("textbox", { name: "Card number", exact: true })
      .fill("4242 4242 4242 4242");
    await page
      .getByTitle("Secure card payment", { exact: true })
      .contentFrame()
      .getByRole("textbox", { name: "Expiry date", exact: true })
      .fill("12/34");
    await page
      .getByTitle("Secure card payment", { exact: true })
      .contentFrame()
      .getByRole("textbox", { name: "CVC", exact: true })
      .fill("123");
  });

  // 6. Click "Start trial"
  await test.step('Click "Start trial"', async () => {
    // 1 fallback locator recorded: Optestra can heal this.
    await page.getByRole("button", { name: "Start trial", exact: true }).click();
  });

  // 7. Expect: the page heading is "Welcome to Pro"
  await test.step('Expect: the page heading is "Welcome to Pro"', async () => {
    await expect(page.locator("h1")).toHaveText("Welcome to Pro");
  });

  // 8. Expect: the URL contains /dashboard
  await test.step("Expect: the URL contains /dashboard", async () => {
    await expect(page).toHaveURL(/\/dashboard/);
  });

  // 9. Go to the billing page
  await test.step("Go to the billing page", async () => {
    // 2 fallback locators recorded: Optestra can heal this.
    await page.getByRole("link", { name: "Billing", exact: true }).click();
  });

  // 10. Expect: the page shows "$0.00 due today"
  await test.step('Expect: the page shows "$0.00 due today"', async () => {
    await expect(page.getByText("$0.00 due today", { exact: true })).toBeVisible();
  });
});
