// Generated by Testament from the environment "local". Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Content hash: 6a2cf2af75a6f88d

import { defineConfig, devices } from "@playwright/test";

// Runs the generated specs with plain Playwright, no Testament needed:
//   npx playwright test -c tests/.testament
// Point them at another site with TESTAMENT_BASE_URL (and TESTAMENT_ALLOWED_DOMAINS).
export default defineConfig({
  testDir: ".",
  testMatch: "*.spec.ts",
  timeout: 300_000,
  retries: 1,
  // The second reporter scrubs secrets out of every trace that is kept; the
  // global teardown does it again after the run, whatever the reporters.
  reporter: [[process.env.CI ? "dot" : "list"], ["./testament.reporter.ts"]],
  globalTeardown: "./testament.teardown.ts",
  use: {
    baseURL: process.env.TESTAMENT_BASE_URL ?? "http://127.0.0.1:4100",
    actionTimeout: 5_000,
    navigationTimeout: 30_000,
    serviceWorkers: "block",
    acceptDownloads: false,
    trace: "retain-on-failure",
    video: "retain-on-failure",
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
    { name: "firefox", use: { ...devices["Desktop Firefox"] } },
    { name: "webkit", use: { ...devices["Desktop Safari"] } },
  ],
});
