// Generated by Testament from tests/billing-zero-due.test.md. Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Recording: tests__billing-zero-due.steps.json (key 70cf52efb1e06858)
// Content hash: f38ecc04d1e80597

import { allowed, expect, test } from "./testament.fixtures";

test.beforeEach(async ({ page }) => {
  // setup: POST /__test/seed
  const seed = await page.request.post(allowed("/__test/seed"), {
    data: { trial: "pro" },
    maxRedirects: 0,
  });
  await expect(seed, "setup: POST /__test/seed").toBeOK();
});

test("A trial costs nothing today", { tag: ["@payments"] }, async ({ page, secrets }) => {
  // Start: /login
  await page.goto("/login");

  const loginParams = { email: "ada@example.com" };
  // 1. Use: flows/login.test.md
  await test.step("Log in (flows/login.test.md)", async () => {
    // 1. Go to /login
    await test.step("Go to /login", async () => {
      await page.goto("/login");
    });

    // 2. Fill "Email" with {{params.email}}
    await test.step('Fill "Email" with {{params.email}}', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("textbox", { name: "Email", exact: true }).fill(loginParams.email);
    });

    // 3. Fill "Password" with {{params.password}}
    await test.step('Fill "Password" with {{params.password}}', async () => {
      // 1 fallback locator recorded: Testament can heal this.
      await secrets.fill(page.getByLabel("Password", { exact: true }), "SHOP_PASSWORD");
    });

    // 4. Click "Log in"
    await test.step('Click "Log in"', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("button", { name: "Log in", exact: true }).click();
    });

    // 5. Expect: the page heading is "Dashboard"
    await test.step('Expect: the page heading is "Dashboard"', async () => {
      await expect(page.locator("h1")).toHaveText("Dashboard");
    });
  });

  // 2. Go to the billing page
  await test.step("Go to the billing page", async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByRole("link", { name: "Billing", exact: true }).click();
  });

  // 3. Expect: the page shows "Pro plan"
  await test.step('Expect: the page shows "Pro plan"', async () => {
    await expect(page.getByText("Pro plan")).toBeVisible();
  });

  // 4. Expect: the page shows "$0.00 due today"
  await test.step('Expect: the page shows "$0.00 due today"', async () => {
    await expect(page.getByText("$0.00 due today", { exact: true })).toBeVisible();
  });
});
