// Generated by Testament from tests/delete-account-guard.test.md. Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Recording: tests__delete-account-guard.steps.json (key a4e3af51fced2081)
// Content hash: 974da0fcdf1944d7

import { allowed, expect, test } from "./testament.fixtures";

test.beforeEach(async ({ page }) => {
  // setup: POST /__test/seed
  const seed = await page.request.post(allowed("/__test/seed"), { maxRedirects: 0 });
  await expect(seed, "setup: POST /__test/seed").toBeOK();
});

test("Settings can be changed without going near account deletion", {
  tag: ["@settings", "@safety"],
  annotation: [
    { type: "testament", description: 'Never: click "Delete account" (checked by Testament only)' },
    {
      type: "testament",
      description: 'Never: click "Yes, delete my account" (checked by Testament only)',
    },
  ],
}, async ({ page, secrets }) => {
  // Start: /login
  await page.goto("/login");

  const loginParams = { email: "ada@example.com" };
  // 1. Use: flows/login.test.md
  await test.step("Log in (flows/login.test.md)", async () => {
    // 1. Go to /login
    await test.step("Go to /login", async () => {
      await page.goto("/login");
    });

    // 2. Fill "Email" with {{params.email}}
    await test.step('Fill "Email" with {{params.email}}', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("textbox", { name: "Email", exact: true }).fill(loginParams.email);
    });

    // 3. Fill "Password" with {{params.password}}
    await test.step('Fill "Password" with {{params.password}}', async () => {
      // 1 fallback locator recorded: Testament can heal this.
      await secrets.fill(page.getByLabel("Password", { exact: true }), "SHOP_PASSWORD");
    });

    // 4. Click "Log in"
    await test.step('Click "Log in"', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("button", { name: "Log in", exact: true }).click();
    });

    // 5. Expect: the page heading is "Dashboard"
    await test.step('Expect: the page heading is "Dashboard"', async () => {
      await expect(page.locator("h1")).toHaveText("Dashboard");
    });
  });

  // 2. Go to the settings page
  await test.step("Go to the settings page", async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByRole("link", { name: "Settings", exact: true }).click();
  });

  // 3. Expect: a "Delete account" button is shown
  await test.step('Expect: a "Delete account" button is shown', async () => {
    await expect(page.getByRole("button", { name: "Delete account", exact: true })).toBeVisible();
  });

  // 4. Select "Asia/Tokyo" in "Time zone"
  await test.step('Select "Asia/Tokyo" in "Time zone"', async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByLabel("Time zone", { exact: true }).selectOption("Asia/Tokyo");
  });

  // 5. Click "Save changes"
  await test.step('Click "Save changes"', async () => {
    // 1 fallback locator recorded: Testament can heal this.
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
  });

  // 6. Expect: a message says "Profile saved"
  await test.step('Expect: a message says "Profile saved"', async () => {
    await expect(page.getByText("Profile saved", { exact: true })).toBeVisible();
  });
});
