// Generated by Testament from the environment "local". Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Content hash: 3e03023ce3854060

import { existsSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { crc32, deflateRawSync, inflateRawSync } from "node:zlib";
import type { Reporter, TestCase, TestResult } from "@playwright/test/reporter";

// Scrubs secrets out of Playwright traces. Playwright's trace records what a
// test types (call parameters), the page's request bodies and the values of
// fields in its DOM snapshots, so a trace kept for a failed test would hold any
// secret that test typed. After each test this reporter rewrites every kept
// trace, replacing each secret's value (as typed, JSON-escaped, URL-encoded and
// base64) with `[secret:NAME]`. A trace it can't rewrite, or still finds a
// secret in afterwards, is deleted: an unscrubbed trace is never kept.
// Plain Node: nothing here needs Testament installed.

// The secrets the tests may type (names only; values come from the environment).
const SECRET_NAMES = ["SHOP_PASSWORD"];

/** Shorter values can't be told apart from ordinary text, so their traces are deleted. */
const MIN_SECRET_LENGTH = 4;
const MARK = "scrubbed by testament";

export interface Secret {
  name: string;
  value: string;
}

/** The declared secrets that have a value in this process's environment. */
export function secretsFromEnv(env: NodeJS.ProcessEnv = process.env): Secret[] {
  return SECRET_NAMES.flatMap((name) => {
    const value = env[name];
    return value ? [{ name, value }] : [];
  });
}

// ── Zip ─────────────────────────────────────────────────────────────────────
// Just enough of the format for traces: stored and deflated entries, no
// encryption, no ZIP64. Anything else throws, and the trace is deleted.

interface Entry {
  name: string;
  data: Buffer;
  time: number;
  date: number;
}

export function readZip(zip: Buffer): { entries: Entry[]; comment: string } {
  let end = -1;
  for (let i = zip.length - 22; i >= Math.max(0, zip.length - 22 - 0xffff); i--) {
    if (zip.readUInt32LE(i) === 0x06054b50) {
      end = i;
      break;
    }
  }
  if (end < 0) throw new Error("not a zip file");
  const count = zip.readUInt16LE(end + 10);
  let offset = zip.readUInt32LE(end + 16);
  if (count === 0xffff || offset === 0xffffffff) throw new Error("ZIP64 is not supported");
  const comment = zip.toString("utf8", end + 22, end + 22 + zip.readUInt16LE(end + 20));
  const entries: Entry[] = [];
  for (let n = 0; n < count; n++) {
    if (zip.readUInt32LE(offset) !== 0x02014b50) throw new Error("bad central directory");
    const flags = zip.readUInt16LE(offset + 8);
    const method = zip.readUInt16LE(offset + 10);
    const time = zip.readUInt16LE(offset + 12);
    const date = zip.readUInt16LE(offset + 14);
    const crc = zip.readUInt32LE(offset + 16);
    const size = zip.readUInt32LE(offset + 20);
    const nameLength = zip.readUInt16LE(offset + 28);
    const extraLength = zip.readUInt16LE(offset + 30);
    const commentLength = zip.readUInt16LE(offset + 32);
    const local = zip.readUInt32LE(offset + 42);
    const name = zip.toString("utf8", offset + 46, offset + 46 + nameLength);
    if (flags & 1) throw new Error(`${name} is encrypted`);
    if (size === 0xffffffff || local === 0xffffffff) throw new Error("ZIP64 is not supported");
    if (zip.readUInt32LE(local) !== 0x04034b50) throw new Error(`bad local header for ${name}`);
    const start = local + 30 + zip.readUInt16LE(local + 26) + zip.readUInt16LE(local + 28);
    const raw = zip.subarray(start, start + size);
    let data: Buffer;
    if (method === 0) data = Buffer.from(raw);
    else if (method === 8) data = inflateRawSync(raw);
    else throw new Error(`${name} uses compression method ${method}`);
    if (crc32(data) !== crc) throw new Error(`${name} is corrupt`);
    entries.push({ name, data, time, date });
    offset += 46 + nameLength + extraLength + commentLength;
  }
  return { entries, comment };
}

export function writeZip(entries: Entry[], comment = ""): Buffer {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;
  for (const entry of entries) {
    const name = Buffer.from(entry.name, "utf8");
    const data = deflateRawSync(entry.data);
    const crc = crc32(entry.data);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0x0800, 6);
    local.writeUInt16LE(8, 8);
    local.writeUInt16LE(entry.time, 10);
    local.writeUInt16LE(entry.date, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(entry.data.length, 22);
    local.writeUInt16LE(name.length, 26);
    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(8, 10);
    central.writeUInt16LE(entry.time, 12);
    central.writeUInt16LE(entry.date, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(data.length, 20);
    central.writeUInt32LE(entry.data.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt32LE(offset, 42);
    locals.push(local, name, data);
    centrals.push(central, name);
    offset += local.length + name.length + data.length;
  }
  const directory = Buffer.concat(centrals);
  const note = Buffer.from(comment, "utf8");
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(directory.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(note.length, 20);
  return Buffer.concat([...locals, directory, end, note]);
}

// ── Scrubbing ───────────────────────────────────────────────────────────────

/** Every way a value shows up in a trace as plain bytes. */
function forms(value: string): string[] {
  const all = new Set([
    value,
    JSON.stringify(value).slice(1, -1),
    encodeURIComponent(value),
    new URLSearchParams({ v: value }).toString().slice(2),
    Buffer.from(value).toString("base64"),
    Buffer.from(value).toString("base64").replace(/=+$/, ""),
    Buffer.from(value).toString("base64url"),
  ]);
  return [...all].filter((form) => form.length > 0).sort((a, b) => b.length - a.length);
}

function replaceAll(data: Buffer, find: Buffer, replacement: Buffer): Buffer {
  let at = data.indexOf(find);
  if (at < 0) return data;
  const parts: Buffer[] = [];
  let last = 0;
  while (at >= 0) {
    parts.push(data.subarray(last, at), replacement);
    last = at + find.length;
    at = data.indexOf(find, last);
  }
  parts.push(data.subarray(last));
  return Buffer.concat(parts);
}

function replaceForms(data: Buffer, secrets: readonly Secret[]): Buffer {
  let out = data;
  for (const secret of secrets) {
    const replacement = Buffer.from(`[secret:${secret.name}]`);
    for (const form of forms(secret.value)) out = replaceAll(out, Buffer.from(form), replacement);
  }
  return out;
}

const BASE64 = /[A-Za-z0-9+/_-]{12,}={0,2}/g;

/** Base64 runs in text (request bodies, headers) are decoded, scrubbed and encoded again. */
function scrubBase64(text: string, secrets: readonly Secret[]): string {
  return text.replace(BASE64, (run) => {
    const url = /[-_]/.test(run);
    const decoded = Buffer.from(run, url ? "base64url" : "base64");
    const scrubbed = replaceForms(decoded, secrets);
    if (scrubbed === decoded) return run;
    const encoded = scrubbed.toString(url ? "base64url" : "base64");
    return run.endsWith("=") || url ? encoded : encoded.replace(/=+$/, "");
  });
}

const isText = (data: Buffer) => !data.subarray(0, 8192).includes(0);

function scrubEntry(data: Buffer, secrets: readonly Secret[]): Buffer {
  const plain = replaceForms(data, secrets);
  if (!isText(plain)) return plain;
  return Buffer.from(scrubBase64(plain.toString("utf8"), secrets), "utf8");
}

/** True when any form of any secret is still in the entry (base64 runs decoded). */
function leaks(data: Buffer, secrets: readonly Secret[]): boolean {
  if (replaceForms(data, secrets) !== data) return true;
  if (!isText(data)) return false;
  const text = data.toString("utf8");
  return [...text.matchAll(BASE64)].some(([run]) => {
    const decoded = Buffer.from(run, /[-_]/.test(run) ? "base64url" : "base64");
    return replaceForms(decoded, secrets) !== decoded;
  });
}

/**
 * Rewrites one trace with the secrets replaced. Deletes it (and says so) when it
 * can't be rewritten or a secret survives. Returns what happened.
 */
export function scrubTrace(
  file: string,
  secrets: readonly Secret[] = secretsFromEnv(),
  warn: (message: string) => void = (message) => process.stderr.write(`${message}\n`),
): "clean" | "scrubbed" | "deleted" {
  if (secrets.length === 0 || !existsSync(file)) return "clean";
  try {
    const short = secrets.find((secret) => secret.value.length < MIN_SECRET_LENGTH);
    if (short) throw new Error(`${short.name} is too short to find reliably`);
    const zip = readFileSync(file);
    const { entries, comment } = readZip(zip);
    if (comment === MARK) return "clean";
    const scrubbed = entries.map((entry) => ({ ...entry, data: scrubEntry(entry.data, secrets) }));
    const changed = scrubbed.some((entry, i) => entry.data !== entries[i]?.data);
    const output = writeZip(scrubbed, MARK);
    if (readZip(output).entries.some((entry) => leaks(entry.data, secrets))) {
      throw new Error("a secret is still in it after scrubbing");
    }
    const temp = `${file}.${process.pid}.tmp`;
    writeFileSync(temp, output);
    renameSync(temp, file);
    return changed ? "scrubbed" : "clean";
  } catch (error) {
    rmSync(file, { force: true });
    warn(
      `Deleted trace ${file}: it could not be scrubbed of secrets (${error instanceof Error ? error.message : String(error)}).`,
    );
    return "deleted";
  }
}

/** Scrubs every trace zip under `dir` (a backstop when this reporter isn't in use). */
export function scrubFolder(dir: string, secrets: readonly Secret[] = secretsFromEnv()): void {
  if (secrets.length === 0 || !existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true, recursive: true })) {
    if (entry.isFile() && entry.name.endsWith(".zip")) {
      scrubTrace(join(entry.parentPath, entry.name), secrets);
    }
  }
}

/** Scrubs the traces kept for each test as soon as it ends. */
export default class SecretScrubber implements Reporter {
  onTestEnd(_test: TestCase, result: TestResult): void {
    for (const attachment of result.attachments) {
      if (attachment.path && attachment.contentType === "application/zip") {
        scrubTrace(attachment.path);
      }
    }
  }

  printsToStdio(): boolean {
    return false;
  }
}
