// Generated by Testament from tests/sort-orders.test.md. Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Recording: tests__sort-orders.steps.json (key cd456fac91c276be)
// Content hash: 4e54e95fa1334851

import { allowed, expect, test } from "./testament.fixtures";

test.beforeEach(async ({ page }) => {
  // setup: POST /__test/seed
  const seed = await page.request.post(allowed("/__test/seed"), { maxRedirects: 0 });
  await expect(seed, "setup: POST /__test/seed").toBeOK();
});

test("Orders can be sorted by total", { tag: ["@tables"] }, async ({ page, secrets }) => {
  // Start: /login
  await page.goto("/login");

  const loginParams = { email: "ada@example.com" };
  // 1. Use: flows/login.test.md
  await test.step("Log in (flows/login.test.md)", async () => {
    // 1. Go to /login
    await test.step("Go to /login", async () => {
      await page.goto("/login");
    });

    // 2. Fill "Email" with {{params.email}}
    await test.step('Fill "Email" with {{params.email}}', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("textbox", { name: "Email", exact: true }).fill(loginParams.email);
    });

    // 3. Fill "Password" with {{params.password}}
    await test.step('Fill "Password" with {{params.password}}', async () => {
      // 1 fallback locator recorded: Testament can heal this.
      await secrets.fill(page.getByLabel("Password", { exact: true }), "SHOP_PASSWORD");
    });

    // 4. Click "Log in"
    await test.step('Click "Log in"', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("button", { name: "Log in", exact: true }).click();
    });

    // 5. Expect: the page heading is "Dashboard"
    await test.step('Expect: the page heading is "Dashboard"', async () => {
      await expect(page.locator("h1")).toHaveText("Dashboard");
    });
  });

  // 2. Go to the orders page
  await test.step("Go to the orders page", async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByRole("link", { name: "Orders", exact: true }).click();
  });

  // 3. Expect: the orders table shows 5 orders
  await test.step("Expect: the orders table shows 5 orders", async () => {
    await expect(
      page.getByRole("table", { name: "Your orders", exact: true }).getByRole("rowheader"),
    ).toHaveCount(5);
  });

  // 4. Click the "Total" column header
  await test.step('Click the "Total" column header', async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByRole("button", { name: "Total", exact: true }).click();
  });

  // 5. Expect: the first order in the table is A-1002 ($8.90)
  await test.step("Expect: the first order in the table is A-1002 ($8.90)", async () => {
    await expect(
      page.getByRole("table", { name: "Your orders", exact: true }).getByRole("rowheader").first(),
    ).toHaveText("A-1002");
  });

  // 6. Click the "Total" column header again
  await test.step('Click the "Total" column header again', async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByRole("button", { name: "Total", exact: true }).click();
  });

  // 7. Expect: the first order in the table is A-1004 ($150.00)
  await test.step("Expect: the first order in the table is A-1004 ($150.00)", async () => {
    await expect(
      page.getByRole("table", { name: "Your orders", exact: true }).getByRole("rowheader").first(),
    ).toHaveText("A-1004");
  });

  // 8. Click "Show refunded orders"
  await test.step('Click "Show refunded orders"', async () => {
    // 1 fallback locator recorded: Testament can heal this.
    await page.getByText("Show refunded orders", { exact: true }).click();
  });

  // 9. Expect: the orders table shows 6 orders
  await test.step("Expect: the orders table shows 6 orders", async () => {
    await expect(
      page.getByRole("table", { name: "Your orders", exact: true }).getByRole("rowheader"),
    ).toHaveCount(6);
  });
});
