// Generated by Testament from tests/allowed-hosts.test.md. Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Recording: tests__allowed-hosts.steps.json (key e8543d291da0548f)
// Content hash: bd5dd2b20cc07f8f

import { checkedByTestament, containing, expect, test } from "./testament.fixtures";

test("Pages only reach allowed hosts", { tag: ["@safety"] }, async ({ page, values, network }) => {
  const data = { email: values.unique.email() };

  // Start: /pricing
  await page.goto("/pricing");

  // 1. Click "Sign up" in the menu
  await test.step('Click "Sign up" in the menu', async () => {
    network.mark();
    // 1 fallback locator recorded: Testament can heal this.
    await page.getByRole("link", { name: "Sign up", exact: true }).click();
  });

  // 2. Expect: the sign-up page was requested from the server
  await test.step("Expect: the sign-up page was requested from the server", async () => {
    await network.expectResponse({ method: "GET", url: "/signup", status: 200 });
  });

  // 3. Fill "Email" with {{data.email}}
  await test.step('Fill "Email" with {{data.email}}', async () => {
    network.mark();
    // 1 fallback locator recorded: Testament can heal this.
    await page.getByLabel("Email", { exact: true }).fill(data.email);
  });

  // 4. Soft: the sign-up form looks tidy
  await test.step("Soft: the sign-up form looks tidy", async () => {
    // Checked by Testament only (a model judges it): never fails or passes this spec.
    checkedByTestament("Soft: the sign-up form looks tidy", "a model judges it");
  });

  // 5. Soft: "Email" contains {{data.email}}
  await test.step('Soft: "Email" contains {{data.email}}', async () => {
    await expect
      .soft(page.getByLabel("Email", { exact: true }))
      .toHaveValue(containing(data.email));
  });

  // 6. Opening a page on another host is refused (code block)
  await test.step("Opening a page on another host is refused", async () => {
    const other = new URL(page.url());
    other.hostname = "localhost";
    await expect(page.goto(other.href)).rejects.toThrow();
    expect(page.url()).not.toContain("localhost");
  });
});
