// Generated by Testament from tests/settings-profile.test.md. Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Recording: tests__settings-profile.steps.json (key e1d3f34fe6b77958)
// Content hash: d332402b271a76be

import { allowed, expect, route, test } from "./testament.fixtures";

test.beforeEach(async ({ page }) => {
  // setup: POST /__test/seed
  const seed = await page.request.post(allowed("/__test/seed"), { maxRedirects: 0 });
  await expect(seed, "setup: POST /__test/seed").toBeOK();
});

test("Profile changes are saved", { tag: ["@settings", "@forms"] }, async ({ page, secrets }) => {
  // Start: /login
  await page.goto("/login");

  const loginParams = { email: "ada@example.com" };
  // 1. Use: flows/login.test.md
  await test.step("Log in (flows/login.test.md)", async () => {
    // 1. Go to /login
    await test.step("Go to /login", async () => {
      await page.goto("/login");
    });

    // 2. Fill "Email" with {{params.email}}
    await test.step('Fill "Email" with {{params.email}}', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("textbox", { name: "Email", exact: true }).fill(loginParams.email);
    });

    // 3. Fill "Password" with {{params.password}}
    await test.step('Fill "Password" with {{params.password}}', async () => {
      // 1 fallback locator recorded: Testament can heal this.
      await secrets.fill(page.getByLabel("Password", { exact: true }), "SHOP_PASSWORD");
    });

    // 4. Click "Log in"
    await test.step('Click "Log in"', async () => {
      // 2 fallback locators recorded: Testament can heal this.
      await page.getByRole("button", { name: "Log in", exact: true }).click();
    });

    // 5. Expect: the page heading is "Dashboard"
    await test.step('Expect: the page heading is "Dashboard"', async () => {
      await expect(page.locator("h1")).toHaveText("Dashboard");
    });
  });

  // 2. Go to the settings page
  await test.step("Go to the settings page", async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByRole("link", { name: "Settings", exact: true }).click();
    await expect(page).toHaveURL(route("/settings"));
  });

  // 3. Fill "Full name" with Ada King
  await test.step('Fill "Full name" with Ada King', async () => {
    // 1 fallback locator recorded: Testament can heal this.
    await page.getByLabel("Full name", { exact: true }).fill("Ada King");
  });

  // 4. Select "Europe/London" in "Time zone"
  await test.step('Select "Europe/London" in "Time zone"', async () => {
    // 2 fallback locators recorded: Testament can heal this.
    await page.getByLabel("Time zone", { exact: true }).selectOption("Europe/London");
  });

  // 5. Click "Save changes"
  await test.step('Click "Save changes"', async () => {
    // 1 fallback locator recorded: Testament can heal this.
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
  });

  // 6. Expect: a message says "Profile saved"
  await test.step('Expect: a message says "Profile saved"', async () => {
    await expect(page.getByText("Profile saved", { exact: true })).toBeVisible();
  });

  // 7. Reload the page
  await test.step("Reload the page", async () => {
    await page.reload();
  });

  // 8. Expect: "Full name" contains "Ada King"
  await test.step('Expect: "Full name" contains "Ada King"', async () => {
    await expect(page.getByLabel("Full name", { exact: true })).toHaveValue(/Ada King/);
  });

  // 9. Expect: "Time zone" is "Europe/London"
  await test.step('Expect: "Time zone" is "Europe/London"', async () => {
    await expect(page.getByLabel("Time zone", { exact: true })).toHaveValue("Europe/London");
  });
});
