// Generated by Testament from the environment "local". Safe to edit: see https://testament.dev/docs/generated-specs
// (Testament won't overwrite a changed file unless you pass --force).
// Content hash: b1d64d0a94b1d67d

import type { FullConfig } from "@playwright/test";
import { scrubFolder } from "./testament.reporter";

/**
 * After the whole run: scrubs secrets out of every trace in the output folders.
 * A backstop for runs where `--reporter` replaced the scrubbing reporter.
 */
export default function scrubAfterRun(config: FullConfig): void {
  for (const project of config.projects) scrubFolder(project.outputDir);
}
